version: "3.6"
services:
  db:
    image: postgres
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "1234" 
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - db
    ports:
      - "5432:5432"
  rest:
    build: ./rest
    ports:
      - "80:8080"
    networks:
      - db
    depends_on: 
      - db
  bot:
    build: ./bot
    networks:
      - db
    depends_on: 
      - db
networks:
  db:
    external: false
    driver: bridge